# Kaggle dataset link
https://www.kaggle.com/datasets/hijest/genre-classification-dataset-imdb

In [1]:
import pandas as pd
file_path="C:/Users/bsai3/Downloads/Genre Classification Dataset/train_data.txt"
with open(file_path,'r',encoding='utf-8') as file:
    data=file.readlines()

In [2]:
records=[]
for line in data:
    record=line.strip().split(":::")
    records.append(record)
records[:5]

[['1 ',
  ' Oscar et la dame rose (2009) ',
  ' drama ',
  ' Listening in to a conversation between his doctor and parents, 10-year-old Oscar learns what nobody has the courage to tell him. He only has a few weeks to live. Furious, he refuses to speak to anyone except straight-talking Rose, the lady in pink he meets on the hospital stairs. As Christmas approaches, Rose uses her fantastical experiences as a professional wrestler, her imagination, wit and charm to allow Oscar to live life and love to the full, in the company of his friends Pop Corn, Einstein, Bacon and childhood sweetheart Peggy Blue.'],
 ['2 ',
  ' Cupid (1997) ',
  ' thriller ',
  ' A brother and sister with a past incestuous relationship have a current murderous relationship. He murders the women who reject him and she murders the women who get too close to him.'],
 ['3 ',
  ' Young, Wild and Wonderful (1980) ',
  ' adult ',
  ' As the bus empties the students for their field trip to the Museum of Natural History, lit

In [3]:
columns=['s.no','movie_name','genre','description']
df=pd.DataFrame(records,columns=columns)
df.head()

s.no                          movie_name       genre  \
0   1        Oscar et la dame rose (2009)       drama    
1   2                        Cupid (1997)    thriller    
2   3    Young, Wild and Wonderful (1980)       adult    
3   4               The Secret Sin (1915)       drama    
4   5              The Unrecovered (2007)       drama    

                                         description  
0   Listening in to a conversation between his do...  
1   A brother and sister with a past incestuous r...  
2   As the bus empties the students for their fie...  
3   To help their unemployed father make ends mee...  
4   The film's title refers not only to the un-re...

In [4]:
df=df.drop(labels=["s.no"],axis=1)
df.head()

movie_name       genre  \
0       Oscar et la dame rose (2009)       drama    
1                       Cupid (1997)    thriller    
2   Young, Wild and Wonderful (1980)       adult    
3              The Secret Sin (1915)       drama    
4             The Unrecovered (2007)       drama    

                                         description  
0   Listening in to a conversation between his do...  
1   A brother and sister with a past incestuous r...  
2   As the bus empties the students for their fie...  
3   To help their unemployed father make ends mee...  
4   The film's title refers not only to the un-re...

In [5]:
df["genre"].unique()

array([' drama ', ' thriller ', ' adult ', ' documentary ', ' comedy ',
       ' crime ', ' reality-tv ', ' horror ', ' sport ', ' animation ',
       ' action ', ' fantasy ', ' short ', ' sci-fi ', ' music ',
       ' adventure ', ' talk-show ', ' western ', ' family ', ' mystery ',
       ' history ', ' news ', ' biography ', ' romance ', ' game-show ',
       ' musical ', ' war '], dtype=object)

In [6]:
df.dropna(inplace=True)

In [7]:
df.isna().sum()

movie_name     0
genre          0
description    0
dtype: int64

In [8]:
df.reset_index(drop=True,inplace=True)

In [9]:
df.head()

movie_name       genre  \
0       Oscar et la dame rose (2009)       drama    
1                       Cupid (1997)    thriller    
2   Young, Wild and Wonderful (1980)       adult    
3              The Secret Sin (1915)       drama    
4             The Unrecovered (2007)       drama    

                                         description  
0   Listening in to a conversation between his do...  
1   A brother and sister with a past incestuous r...  
2   As the bus empties the students for their fie...  
3   To help their unemployed father make ends mee...  
4   The film's title refers not only to the un-re...

In [10]:
labels={}
num=0
for i in df.genre.unique():
    if i not in labels:
        labels[i]=num
        num=num+1
labels

{' drama ': 0,
 ' thriller ': 1,
 ' adult ': 2,
 ' documentary ': 3,
 ' comedy ': 4,
 ' crime ': 5,
 ' reality-tv ': 6,
 ' horror ': 7,
 ' sport ': 8,
 ' animation ': 9,
 ' action ': 10,
 ' fantasy ': 11,
 ' short ': 12,
 ' sci-fi ': 13,
 ' music ': 14,
 ' adventure ': 15,
 ' talk-show ': 16,
 ' western ': 17,
 ' family ': 18,
 ' mystery ': 19,
 ' history ': 20,
 ' news ': 21,
 ' biography ': 22,
 ' romance ': 23,
 ' game-show ': 24,
 ' musical ': 25,
 ' war ': 26}

In [11]:
def replace_labels(target):
    return labels[target]
df["target"]=df["genre"].map(replace_labels)
df.head()

movie_name       genre  \
0       Oscar et la dame rose (2009)       drama    
1                       Cupid (1997)    thriller    
2   Young, Wild and Wonderful (1980)       adult    
3              The Secret Sin (1915)       drama    
4             The Unrecovered (2007)       drama    

                                         description  target  
0   Listening in to a conversation between his do...       0  
1   A brother and sister with a past incestuous r...       1  
2   As the bus empties the students for their fie...       2  
3   To help their unemployed father make ends mee...       0  
4   The film's title refers not only to the un-re...       0

In [12]:
x=df["description"]
y=df["target"]
x,y

(0         Listening in to a conversation between his do...
 1         A brother and sister with a past incestuous r...
 2         As the bus empties the students for their fie...
 3         To help their unemployed father make ends mee...
 4         The film's title refers not only to the un-re...
                                ...                        
 54209     This short-lived NBC live sitcom centered on ...
 54210     The NEXT Generation of EXPLOITATION. The sist...
 54211     Ze bestaan echt, is a stand-up comedy about g...
 54212     Walter and Vivian live in the country and hav...
 54213     On Labor Day Weekend, 1935, the most intense ...
 Name: description, Length: 54214, dtype: object,
 0         0
 1         1
 2         2
 3         0
 4         0
          ..
 54209     4
 54210     7
 54211     3
 54212     4
 54213    20
 Name: target, Length: 54214, dtype: int64)

In [13]:
len(x.unique())

54086

In [14]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Embedding,SimpleRNN,LSTM,Dense

In [15]:
import nltk
import re
from nltk.corpus import stopwords

In [16]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\bsai3\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [17]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
corpus_train=[]
for i in range(0,len(x)):
        review=re.sub('[^a-zA-Z]',' ',x[i])
        review=review.lower()
        review=review.split()
        review=[ps.stem(word)for word in review if not word in stopwords.words('english')]
        review=' '.join(review)
        corpus_train.append(review)

In [18]:
corpus_train

['listen convers doctor parent year old oscar learn nobodi courag tell week live furiou refus speak anyon except straight talk rose ladi pink meet hospit stair christma approach rose use fantast experi profession wrestler imagin wit charm allow oscar live life love full compani friend pop corn einstein bacon childhood sweetheart peggi blue',
 'brother sister past incestu relationship current murder relationship murder women reject murder women get close',
 'bu empti student field trip museum natur histori littl tour guid suspect student anoth tour first lectur film co drift dream erot fantasi one imagin film releas emot fantasi erot uncommon way one slip curat offic littl acquisit anoth find anthropologist see bone identifi even head teacher immun soon tour bu depart everyon admit quit educ',
 'help unemploy father make end meet edith twin sister grace work seamstress invalid grace fall prey temptat chinatown opium becom addict condit worsen misguid physician prescrib morphin eas pain 

In [19]:
corpus_train=pd.Series(corpus_train)
len(corpus_train.unique())

54074

In [20]:
vocab_size=54075

In [21]:
onehot=[one_hot(words,vocab_size)for words in corpus_train] 
onehot

[[21948,
  33748,
  3145,
  697,
  22211,
  14224,
  18408,
  26901,
  38955,
  960,
  6839,
  12889,
  7535,
  48968,
  37433,
  26902,
  2399,
  29782,
  7609,
  47201,
  550,
  3918,
  31965,
  42579,
  9619,
  19941,
  30867,
  41595,
  550,
  30294,
  14268,
  35717,
  49663,
  49647,
  39499,
  2062,
  18672,
  8081,
  18408,
  7535,
  52702,
  467,
  20178,
  50551,
  36876,
  2446,
  49633,
  31620,
  41860,
  48314,
  14336,
  20458,
  5714],
 [22115,
  5195,
  46485,
  41365,
  13419,
  11257,
  37809,
  13419,
  37809,
  25578,
  27884,
  37809,
  25578,
  42630,
  20058],
 [18966,
  80,
  37200,
  29466,
  1338,
  52286,
  43661,
  13925,
  8239,
  44346,
  11985,
  43123,
  37200,
  24521,
  44346,
  53415,
  8154,
  24949,
  11277,
  20509,
  39533,
  28354,
  41025,
  49995,
  39499,
  24949,
  17189,
  42335,
  41025,
  28354,
  17118,
  4459,
  49995,
  49519,
  22521,
  12990,
  8239,
  35262,
  24521,
  7885,
  41120,
  51759,
  23934,
  34320,
  4430,
  14770,
  307

In [23]:
nltk.download('punkt')
max_words=max(len(nltk.word_tokenize(review)) for review in corpus_train)
max_words

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\bsai3\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


1614

In [24]:
sent_length=1615
emb_vec=pad_sequences(onehot,padding='pre',maxlen=sent_length)
print(emb_vec)

[[    0     0     0 ... 14336 20458  5714]
 [    0     0     0 ... 25578 42630 20058]
 [    0     0     0 ... 11920  5629 16236]
 ...
 [    0     0     0 ... 15173 44324  9332]
 [    0     0     0 ...  7885  7218  1338]
 [    0     0     0 ...   314 18047 12807]]


In [25]:
embedding_vector_features=100
RNN=Sequential()
RNN.add(Embedding(input_dim=vocab_size,output_dim=embedding_vector_features,input_length=sent_length))
RNN.add(SimpleRNN(units=100))
RNN.add(Dense(units=27,activation='softmax'))
RNN.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
print(RNN.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 1615, 100)         5407500   
                                                                 
 simple_rnn (SimpleRNN)      (None, 100)               20100     
                                                                 
 dense (Dense)               (None, 27)                2727      
                                                                 
Total params: 5430327 (20.72 MB)
Trainable params: 5430327 (20.72 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [26]:
RNN.fit(emb_vec,y,epochs=10,batch_size=32)

Epoch 1/10
1695/1695 [==============================] - 654s 385ms/step - loss: 2.3739 - accuracy: 0.2943
Epoch 2/10
1695/1695 [==============================] - 574s 339ms/step - loss: 2.2035 - accuracy: 0.3699
Epoch 3/10
1695/1695 [==============================] - 544s 321ms/step - loss: 2.0173 - accuracy: 0.4357
Epoch 4/10
1695/1695 [==============================] - 535s 316ms/step - loss: 1.8883 - accuracy: 0.4695
Epoch 5/10
1695/1695 [==============================] - 587s 346ms/step - loss: 1.7358 - accuracy: 0.5034
Epoch 6/10
1695/1695 [==============================] - 575s 339ms/step - loss: 1.4321 - accuracy: 0.5912
Epoch 7/10
1695/1695 [==============================] - 619s 365ms/step - loss: 1.4473 - accuracy: 0.5839
Epoch 8/10
1695/1695 [==============================] - 611s 361ms/step - loss: 1.2020 - accuracy: 0.6570
Epoch 9/10
1695/1695 [==============================] - 561s 331ms/step - loss: 1.0311 - accuracy: 0.7045
Epoch 10/10
1695/1695 [=======================

In [29]:
file_path="C:/Users/bsai3/Downloads/Genre Classification Dataset/test_data.txt"
with open(file_path,'r',encoding='utf-8') as file:
    data_test=file.readlines()
    records_test=[]
    for line in data_test:
        record=line.strip().split(":::")
        records_test.append(record)
columns=['s.no','movie_name','description']
df_test=pd.DataFrame(records_test,columns=columns)
x_test=df_test["description"]
corpus_test=[]
for i in range(0,len(x_test)):
        review=re.sub('[^a-zA-Z]',' ',x_test[i])
        review=review.lower()
        review=review.split()
        review=[ps.stem(word)for word in review if not word in stopwords.words('english')]
        review=' '.join(review)
        corpus_test.append(review)
onehot=[one_hot(words,vocab_size)for words in corpus_test]
emb_vec_test=pad_sequences(onehot,padding='pre',maxlen=sent_length)

In [30]:
predictions=RNN.predict(emb_vec_test)

1694/1694 [==============================] - 141s 83ms/step


In [32]:
import numpy as np
predicted_labels=np.argmax(predictions,axis=1)

In [33]:
print(predicted_labels)

[ 3 15  3 ...  3 17  7]
